### ISSUE TITLE
Revenir à la version 1.14.4 de numworks

### ISSUE THREAD

**Issue by Draconic112** [M4xi1m3/nw-external-apps#13]
Bonjour,
Je voulais installé Omega, mais j'avais fait la maj 1.16 avant...
J'aimerais donc trouver un moyen de repasser ma calculatrice sur une version 1.14.4. Cela est il possible ?
Merci d'avance pour l'aide

Version du logiciel : 1.16.3
FCC ID : 2ALWP-N0110

**Comment by RedGl0w** [comment]
Bonjour
Pour répondre, bien que le repository sur lequel l'issue est ouvert n'a pas de lien avec ça, il n'est pas possible de revenir à une version ancienne sur n0110 (mais c'est possible sur n0100).
Pour d'autres questions, n'hésitez pas à rejoindre notre Discord, ou nous risquons d'être plus réactif.
Bonne fin de week end

**Comment by Draconic112** [comment]
Ha... Bon bah merci quand même ! Bonne fin de week-end à vous aussi !
