### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ghost** [M4xi1m3/nw-external-apps#8]
This repository has no licensing files nor even a copyright notice, therefore this is proprietary software. I can understand why things have no licensing currently, but we should work to get every program to provide a license copy. I would say the same for the api and other stuff in this repo.

I feel this is something that needs to be addressed so people can include the api or other files in their own repositories legally. If there ever is to be an Omega app store, this is something that needs to be taken care of.

**Comment by ghost** [comment]
Oh I see. I just looked at the zardam repo and someone said a similar thing. So until we get that resolved, it will be hard to move forward.

**Comment by quentinguidee** [comment]
(cfr. https://github.com/zardam/nw-external-apps/issues/6)

**Comment by fmlatghor** [comment]
Though it's worth mentioning that some people that are able to be contacted or we know who made which app can decide what license to use. Like HexEdit can have whatever license boricj chooses. I think we should work to getting everyone who made these apps to choose a licenses, then we can deal with zardam's stuff later.

**Comment by fmlatghor** [comment]
So I found that most of the apps do have licenses and copyright, but they aren't included. Most of the apps are infringing on copyright. I'll fix this tomorrow so that all the apps have their respective license copy/copyright. Though things that zardam made changes will become sticky. Hopefully zardam becomes active again.

**Comment by fmlatghor** [comment]
No, nevermind, I don't have legal permissions to do this. I'll figure some way to settle this.
